name: Sync to Hugging Face space

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up remote
        env: 
          HF: ${{ secrets.HG }}
        run: |
          git remote remove space || true
          git remote add space https://ashandilgith:${HF}@huggingface.co/spaces/ashandilgith/demo2

      - name: Push to Hugging Face Space
        run: git push --force space main
