name: Sync to Hugging Face space
on:
  push:
    branches: [main]

  #run this workflow manually from the actions tab
  workflow_dispatch:
  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: add remote
        env: 
          HF: ${{ secrets.HG }}
        run:  git remote add space https://ashandilgith:HG@huggingface.co/spaces/ashandilgith/demo2
      - name: push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force git remote add space https://ashandilgith:HG@huggingface.co/spaces/ashandilgith/demo2 main


          
